# Generated by Django 2.2.3 on 2019-12-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
                ('data_image', models.ImageField(blank=True, upload_to='data_imgs')),
                ('additional_desc', models.TextField()),
            ],
            bases=('blog.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_imgs'),
        ),
    ]
