# Generated by Django 2.2.3 on 2020-01-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191206_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataAnalysis',
        ),
    ]
