# Generated by Django 2.2.3 on 2019-09-01 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 12, 55, 5, 400279), verbose_name='date published'),
        ),
    ]
