# Generated by Django 2.2.3 on 2019-09-01 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190901_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 15, 57, 5, 268908), verbose_name='date published'),
        ),
    ]
