# Generated by Django 2.2.3 on 2019-09-04 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190901_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 4, 14, 21, 32, 698643), verbose_name='date published'),
        ),
    ]
