# Generated by Django 2.2.3 on 2019-09-06 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190904_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 11, 56, 12, 60646), verbose_name='date published'),
        ),
    ]
