# Generated by Django 2.2.3 on 2019-09-15 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190906_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 17, 25, 13, 649581), verbose_name='date published'),
        ),
    ]
