# Generated by Django 2.2.3 on 2019-09-15 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190915_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 23, 4, 14, 76408), verbose_name='date published'),
        ),
    ]
