# Generated by Django 2.2.3 on 2019-09-15 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190915_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 23, 22, 48, 204779), verbose_name='date published'),
        ),
    ]
