# Generated by Django 2.2.3 on 2019-12-01 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190915_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 19, 56, 44, 367222), verbose_name='date published'),
        ),
    ]
