# Generated by Django 2.2.3 on 2019-12-02 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20191201_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 14, 55, 25, 113213), verbose_name='date published'),
        ),
    ]
