# Generated by Django 2.2.3 on 2019-12-03 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20191202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 15, 46, 7, 668312), verbose_name='date published'),
        ),
    ]
