# Generated by Django 2.2.3 on 2019-12-06 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20191202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 19, 35, 14, 19822), verbose_name='date published'),
        ),
    ]
