# Generated by Django 2.2.3 on 2019-12-03 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20191203_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 15, 57, 12, 78609), verbose_name='date published'),
        ),
    ]
