# Generated by Django 2.2.3 on 2019-12-03 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20191203_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 17, 55, 4, 88210), verbose_name='date published'),
        ),
    ]
