# Generated by Django 2.2.3 on 2019-12-04 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20191203_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 23, 34, 15, 260330), verbose_name='date published'),
        ),
    ]
