# Generated by Django 2.2.3 on 2019-12-04 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20191204_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 23, 37, 16, 568013), verbose_name='date published'),
        ),
    ]
