# Generated by Django 2.2.3 on 2019-12-05 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20191204_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 0, 33, 53, 440015), verbose_name='date published'),
        ),
    ]
