# Generated by Django 2.2.3 on 2019-12-05 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20191205_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 13, 27, 48, 571513), verbose_name='date published'),
        ),
    ]
