# Generated by Django 2.2.3 on 2019-12-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20191206_1906'),
        ('polls', '0013_auto_20191206_1935'),
    ]

    operations = [
    ]
